---
title: Gerardo Ortega
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:		
  scope:		
    path: ""		
    type: "posts"		
  values: 		
    description:		
    author: "Gerardo Ortega"		
    cover:		
    ref:		
    lang: "es"
    
plugins:
- jekyll-archives
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate

exclude:
- "/vendor/"
subtitle: A personal journey into the matrix
email: g3ortega@gmail.com
name: Gerardo Ortega
description: "Personal blog of Gerardo Ortega. Topics: Software Engineering, Data Science, Photography and Art. Blog personal de Gerardo Ortega."
base_url: "/"
url: https://g3ortega.com
cover: assets/header.jpg
logo: assets/logo.png
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
jekyll-archives:
  enabled: [categories, tags]
  layout: 'archive'
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
disqus_shortname: g3ortega
ga_tracking_id: UA-39169311-1
descriptions:
- cat: elixir
  desc: My way in Elixir
- cat: ruby
  desc: A little of ruby
- cat: phoenix
  desc: Phoenix Framework
- cat: self
  desc: Opinions
- cat: react
  desc: ReactJS and React Native
- cat: ai
  desc: Artificial Intelligence
- cat: machine_learning
  desc: Machine Learning
social:
- name: Twitter
  icon: twitter
  username: g3ortega
  url: https://twitter.com/g3ortega
  desc: Follow me on Twitter
  share: true
- name: Facebook
  icon: facebook
  username: g3ortega
  url: 
  desc: Friend me on Facebook
  share: true
- name: GitHub
  icon: github
  username: g3ortega
  url: https://github.com/g3ortega
  desc: Fork me on GitHub
  share: false
- name: LinkedIn
  icon: linkedin
  username: Gerardo Ortega
  url: https://www.linkedin.com/in/g3ortega
  desc: Connect with me on LinkedIn
  share: true
- name: Google+
  icon: google-plus
  username: 
  url: 
  desc: Add me to your Circles
  share: true
- name: Tumblr
  icon: tumblr
  username: 
  url: 
  desc: Follow me on Tumblr
  share: false
twitter:
  username: g3ortega
protocols:
  fb_image: assets/logo.png
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: assets/logo.png
  os_repo: https://github.com/g3ortega/g3ortega.github.com
  os_rcs_type: git
  os_src: git@github.com:g3ortega/g3ortega.github.com.git
